export const ACTION_MODES = {
    REPLACE_DATA: 'REPLACE_DATA',
    APPEND_DATA: 'APPEND_DATA',
    PREPEND_DATA: 'PREPEND_DATA',
};

export const ACTIONS = {
    FETCH_PRINTERS: 'FETCH_PRINTERS',
    FETCH_PRINTER: 'FETCH_PRINTER',
    FETCH_IN_USE_PINS: 'FETCH_IN_USE_PINS',

    FETCH_NOTES: 'FETCH_NOTES',
    SAVE_NOTE: 'SAVE_NOTE',
    DUPLICATE_NOTE: 'DUPLICATE_NOTE',
    RENAME_NOTE: 'RENAME_NOTE',
    REMOVE_NOTE: 'REMOVE_NOTE',
};

export const MUTATIONS = {
    SET_AS_LOADING: 'SET_AS_LOADING',

    SET_PRINTERS: 'SET_PRINTERS',
    SET_PRINTER: 'SET_PRINTER',
    SET_IN_USE_PINS: 'SET_IN_USE_PINS',

    SET_NOTES: 'SET_NOTES',
    ADD_NOTE: 'ADD_NOTE',
    SET_NOTE_NAME: 'SET_NOTE_NAME',
    DELETE_NOTE: 'DELETE_NOTE',
};
